### ISSUE TITLE
Solid start!

### ISSUE THREAD

**Issue by eugene1g** [conveyor-mq/conveyor-mq#1]
Hi Jason,

Just wanted to say 'thank you' for your effort in setting up a reliable queue library. The NodeJS ecosystem is surprisingly limited when it comes to _solid_ low-level libraries (e.g. networking, database drivers, etc), and yours will be a most welcome addition. Thanks!

**Comment by jasrusable** [comment]
Hey @eugene1g, thanks for the appreciation! Hopefully, this library can be useful for you and others.

**Comment by glensc** [comment]
Can you add to readme brief about project history, why it was born, what problems it does solve better than alternatives, what were the inspirations when developing this library.

Thanks ahead.

**Comment by jasrusable** [comment]
Hey @glensc, great idea :) I'll add those topics to the README. Thanks!

**Comment by glensc** [comment]
@jasrusable please post to this thread when updating something (i've subscribed to the issue)

**Comment by falkenhawk** [comment]
@jasrusable Thanks for creating this library. It looks very promising.
Your advertisings in `bee-queue` repo caught my attention. I like that it's written in typescript, very well documented and that you have clear goals of making things better than other not-really-production-ready packages.

I am also curious about your opinion on redis v5.0+ streams. (re: https://github.com/bee-queue/bee-queue/pull/112#issuecomment-634226074) I've found https://github.com/mugli/orkid-node where they went for redis streams, but the development seems to be stalled there.

**Comment by jasrusable** [comment]
> @jasrusable Thanks for creating this library. It looks very promising.
> Your advertisings in `bee-queue` repo caught my attention. I like that it's written in typescript, very well documented and that you have clear goals of making things better than other not-really-production-ready packages.
> 
> I am also curious about your opinion on redis v5.0+ streams. (re: [bee-queue/bee-queue#112 (comment)](https://github.com/bee-queue/bee-queue/pull/112#issuecomment-634226074)) I've found https://github.com/mugli/orkid-node where they went for redis streams, but the development seems to be stalled there.

Thanks for your comment :)

**Regarding my thoughts on steams:**
In general, I think Redis streams are great and that they are certainly a very useful primitive to have on Redis.

**In terms of the benefit of steams to Conveyor, two main things:**
  1. I think streams would be able to reduce some of the complexity around the way in which tasks are acquired by workers but performance-wise and reliability-wise I don't see much benefit. I do think that the reduced complexity may justify changing the current `list + brpoplpush` implementation to streams at some point.

  2. The distributed communication between workers, managers and listeners is currently implemented using Redis pub/sub and so is not currently reliable (in the distributed system sense). Switching this over to streams would be very beneficial in that the communication could then be fully reliable.

The only downsides to streams I see in terms of Conveyor is that of having to force users to use Redis >= 5, which will obviously become less of a concern over time as people migrate to newer Redis versions but should still be considered for now. In any case, I will most probably be migrating at least the communication systems over to streams in the medium term to take advantage of the reliability it offers.
