### ISSUE TITLE
Task dispatcher 

### ISSUE THREAD

**Issue by glensc** [conveyor-mq/conveyor-mq#10]
I'm using resque so far, in comparison seems I need to dispatch myself different kind of jobs, i.e if I have jobs that do different tasks, but worker can take only one "handler" which means I must embed a "class" in "data" and dispatch to appropriate handler in the handler method.

Could you perhaps add example task dispatcher which could resolve the actual task via "class" (or more appropriate) key in "data".

The dispatcher is probably trivial, but would be nice if the library takes the problem as first citizen.

**Comment by jasrusable** [comment]
Hey @glensc, great suggestion! I'll add an example and a section in the docs for this.

**Comment by jasrusable** [comment]
Hey, @glensc 👋 Let me know if the example in https://github.com/conveyor-mq/conveyor-mq/pull/11 is what you are referring to regarding dispatching on different kinds of jobs in a single queue?

**Comment by glensc** [comment]
@jasrusable #11 is exactly what I had in mind. thanks!

**Comment by jasrusable** [comment]
Great, I've merged that into the `examples` directory for reference now :)
