### ISSUE TITLE
repeated / recurring job - feature request

### ISSUE THREAD

**Issue by dougg0k** [conveyor-mq/conveyor-mq#165]
Hi,

Any plans on adding a repeated job feature with a cronjob like setup? It could, at least for me, take the need to use something like breejs away, in some cases at least.

**Comment by jasrusable** [comment]
Not for the time being, I'd prefer to keep this library focused solely on task queueing. Having said that, you can already implement primitive repeated job behaviour by enqueuing a job in a worker with a delay https://github.com/conveyor-mq/conveyor-mq#scheduled-tasks
