### ISSUE TITLE
dependencies cleanup

### ISSUE THREAD

**Issue by falkenhawk** [conveyor-mq/conveyor-mq#68]
Would you consider cleaning the project dependencies a bit?
https://bundlephobia.com/result?p=conveyor-mq@0.0.36

- all `@types/` should go to `devDependencies`
- consider ditching `lodash` (I suppose all of the used helper functions can be easily refactored into pure typescript)
- maybe also find a way to reduce the dependency tree by replacing `moment` (it's actually the biggest dependency) with native Date and small helpers

**Comment by jasrusable** [comment]
Hey @falkenhawk 👋 

Thanks for the great suggestions!

> all @types/ should go to devDependencies

This has been merged now in https://github.com/conveyor-mq/conveyor-mq/pull/69

> consider ditching lodash (I suppose all of the used helper functions can be easily refactored into pure typescript)

> maybe also find a way to reduce the dependency tree by replacing moment (it's actually the biggest dependency) with native Date and small helpers

Both good ideas, I will add these to my backlog. `moment` has actually mostly been removed from the codebase, there are just one or two instances of it left before I can remove the dep entirely.

**Comment by jasrusable** [comment]
Released [0.0.37](https://github.com/conveyor-mq/conveyor-mq/releases/tag/v0.0.37) with all typings moved to devDeps (As well as other dep updates).

**Comment by falkenhawk** [comment]
heads up: momentjs is ~dead~ _done_
https://momentjs.com/docs/#/-project-status/

**Comment by jasrusable** [comment]
@falkenhawk Thanks for the heads up on this, I saw the announcement yesterday and evaluated some alternatives and Ill most probably be switching the codebase over to [date-fns](https://date-fns.org/) or [luxon](https://moment.github.io/luxon/) in the near future.

**Comment by dougg0k** [comment]
A lightweight option https://day.js.org/ If the project is not dead, is it?

**Comment by jasrusable** [comment]
Tracking these suggestions ^ in separate issues now: https://github.com/conveyor-mq/conveyor-mq/issues/168 and https://github.com/conveyor-mq/conveyor-mq/issues/167.
